---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: counter-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: counter-service
  policy:
    semver:
      range: 0.0.x
