apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: prod
spec:
  selector:
    app: counter-service
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: prod
spec:
  selector:
    matchLabels:
      app: counter-service
  replicas: 2
  template:
    metadata:
      namespace: prod
      labels:
        app: counter-service
    spec:
      volumes:
        - name: counter-pv-storage
          persistentVolumeClaim:
            claimName: counter-pv-claim
      containers:
        - name: counter-service
          image: 630943284793.dkr.ecr.us-west-1.amazonaws.com/counter-service:0.0.154 # {"$imagepolicy": "flux-system:counter-service"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/app/counter-volume.ini"
              name: counter-pv-storage
