---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: counter-service
  namespace: flux-system
spec:
  image: 630943284793.dkr.ecr.us-west-1.amazonaws.com/counter-service
  interval: 1m0s

