---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter-pv
  namespace: prod
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: local
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/app/counter-volume.ini"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-pv-claim
  namespace: prod
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
